plugins:
  postal_webhook_public_key:
    default: your_postal_webhook_public_key
    client: false
  discourse_base_url:
    default: https://some-url.com
    client: false
  discourse_api_key:
    default: some-api-key
    client: false
  discourse_api_username:
    default: api_username
    client: false
